version: "3.3"
services:
  b-hunters-wapiti:
    build: ./
    volumes:
      - ./b-hunters.ini:/etc/b-hunters/b-hunters.ini
    environment:
      - modules=backup,brute_login_form,cms,cookieflags,crlf,csp,csrf,exec,file,htaccess,htp,http_headers,https_redirect,ldap,log4shell,methods,network_device,nikto,permanentxss,redirect,shellshock,spring4shell,sql,ssl,ssrf,takeover,timesql,upload,wapp,wp_enum,xss,xxe
  # env_file:
    #   - ./.env